using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace WerkonWebServicesRatchet.Migrations
{
    /// <inheritdoc />
    public partial class AddVisitNumber : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                ALTER TABLE "Visits" ADD COLUMN "Number" bigint NULL;

                WITH ordered AS (
                    SELECT "Id", ROW_NUMBER() OVER (ORDER BY "CreatedAtUtc", "Id") AS rn
                    FROM "Visits"
                )
                UPDATE "Visits" AS v
                SET "Number" = o.rn
                FROM ordered AS o
                WHERE v."Id" = o."Id";

                ALTER TABLE "Visits" ALTER COLUMN "Number" SET NOT NULL;
                ALTER TABLE "Visits" ALTER COLUMN "Number" ADD GENERATED BY DEFAULT AS IDENTITY;

                SELECT CASE
                    WHEN EXISTS (SELECT 1 FROM "Visits") THEN
                        setval(
                            pg_get_serial_sequence('"Visits"', 'Number'),
                            (SELECT MAX("Number") FROM "Visits"),
                            true)
                    ELSE
                        setval(
                            pg_get_serial_sequence('"Visits"', 'Number'),
                            1,
                            false)
                END;
                """);

            migrationBuilder.CreateIndex(
                name: "IX_Visits_Number",
                table: "Visits",
                column: "Number",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Visits_Number",
                table: "Visits");

            migrationBuilder.DropColumn(
                name: "Number",
                table: "Visits");
        }
    }
}
